name: "sklearn fastapi aws lambda"
description: "deploy a fastapi REST api to AWS lambda suing serverless framework"
inputs:
  service_name:
    description: The name of the api
    required: true
  stage:
    description: The stage to deploy the API to
    required: true
  aws_default_region:
    description: The aws region to deploy the API to
    required: true
  aws_s3_bucket:
    description: The aws s3 bucket where the sklearn model is stored
    required: true
  model_key:
    description: The key in the s3 bucket to retrieve the sklearn model
    required: true
  model_version:
    description: The version id of the ml model artifact stored in s3 bucket
    required: true
  worker_timeout:
    description: The timeout to apply to the lambda worker default = 10
    required: false
    default: "10"
outputs:
  endpoint:
    description: "The http endpoint where the model is deployed"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{inputs.service_name}}
    - ${{ inputs.stage }}
    - ${{ inputs.aws_default_region }}
    - ${{ inputs.aws_s3_bucket }}
    - ${{ inputs.model_key }}
    - ${{ inputs.model_version }}
    - ${{ inputs.worker_timeout }}
